name: Terraform Workflow

on:
  push:
    branches:
      - main
      - 

    paths:
      - 'terraform/**'
      - '.github/workflows/**'


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 
        

      - name: Change directory to 'terraform'
        run: cd terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
