name: Terraform Workflow

on:
  push:
    branches:
      - 'venkat/git_workflows' 

jobs:
  build-terraform:
    defaults:
      run:
        working-directory: ./terraform/  

    runs-on: ubuntu-latest

    

   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
    

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
      - name : Terraform Apply
        run: terraform apply -auto-approve

      - name: Get S3 Website URL
        run: terraform output s3_website_url
        

       

      
      
      
